components_manager:
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 2

    default_task_processor: main-task-processor
    fs_task_processor: fs-task-processor

    components:
        server:
            listener:
                port: 8080
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stdout'
                    level: info
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor

        http-client: {}

        handler-graph:
            path: /api/v1/graph
            method: GET
            task_processor: main-task-processor
            genius-api-token: $genius_token
            genius-base-url: https://api.genius.com
            songs-limit: 50

        handler-index:
            path: /
            method: GET
            task_processor: main-task-processor
            file-path: front/index.html
            content-type: 'text/html; charset=utf-8'

        handler-script:
            path: /script.js
            method: GET
            task_processor: main-task-processor
            file-path: front/script.js
            content-type: 'application/javascript; charset=utf-8'