
genius_redirect_uri: http://localhost:8080/auth/callback

cookie_secure: true

db_connection_string: postgresql://CHANGEME_user:CHANGEME_password@localhost:5432/CHANGEME_db

enrichment_base_url: http://localhost:8081

auth_base_url: http://localhost:8083

yandex_gateway_base_url: http://localhost:8090
