
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: six-feat
    metrics_path: /metrics
    params:
      format: [prometheus]
    static_configs:
      - targets: ["six-feat:8085"]
        labels:
          service: six-feat

  - job_name: six-feat-enrichment
    metrics_path: /metrics
    params:
      format: [prometheus]
    static_configs:
      - targets: ["six-feat-enrichment:8086"]
        labels:
          service: six-feat-enrichment

  - job_name: six-feat-genius-gateway
    metrics_path: /metrics
    params:
      format: [prometheus]
    static_configs:
      - targets: ["six-feat-genius-gateway:8087"]
        labels:
          service: six-feat-genius-gateway

  - job_name: six-feat-auth
    metrics_path: /metrics
    params:
      format: [prometheus]
    static_configs:
      - targets: ["six-feat-auth:8088"]
        labels:
          service: six-feat-auth

  - job_name: six-feat-game
    metrics_path: /metrics
    params:
      format: [prometheus]
    static_configs:
      - targets: ["six-feat-game:8089"]
        labels:
          service: six-feat-game
