export const $ = (id) => document.getElementById(id);

export const els = {
  searchModal: $("search-modal"),
  heroForm: $("hero-form"),
  heroInput: $("hero-input"),
  chips: $("chips"),
  chipsLabel: $("chips-label"),

  canvasChrome: $("canvas-chrome"),
  appCanvas: $("app-canvas"),
  canvasDecorator: $("canvas-decorator"),
  canvasState: $("canvas-state"),
  brand: $("brand"),

  btnRoleFilters: $("btn-role-filters"),
  filterBar: $("filter-bar"),

  network: $("network"),
  status: $("status"),
  seedCard: $("seed-card"),
  seedCardAvatar: $("seed-card-avatar"),
  seedCardName: $("seed-card-name"),
  truncationBanner: $("truncation-banner"),
  scanStatusBadge: $("scan-status-badge"),
  scanStatusText: $("scan-status-text"),
  infoBtn: $("info-btn"),
  infoPopover: $("info-popover"),
  rateLimitBadge: $("rate-limit-badge"),
  helpBtn: $("help-btn"),
  helpOverlay: $("help-overlay"),
  helpClose: $("help-close"),
  loading: $("loading"),
  toast: $("toast"),

  canvasFilterFeatured: $("canvas-filter-featured"),
  canvasFilterProducer: $("canvas-filter-producer"),
  canvasFilterWriter: $("canvas-filter-writer"),

  heroFilterFeatured: $("hero-filter-featured"),
  heroFilterProducer: $("hero-filter-producer"),
  heroFilterWriter: $("hero-filter-writer"),

  heroModeSwitch: $("hero-mode-switch"),
  heroModeTabExplore: $("hero-mode-tab-explore"),
  heroModeTabConnect: $("hero-mode-tab-connect"),
  heroModeTabGame: $("hero-mode-tab-game"),
  heroModePanelExplore: $("hero-mode-panel-explore"),
  heroModePanelConnect: $("hero-mode-panel-connect"),
  heroModePanelGame: $("hero-mode-panel-game"),

  heroPathFromInput: $("hero-path-from-input"),
  heroPathToInput: $("hero-path-to-input"),
  btnHeroRunPath: $("btn-hero-run-path"),
  btnHeroSwapPath: $("btn-hero-swap-path"),
  btnHeroClearPath: $("btn-hero-clear-path"),
  heroHopChain: $("hero-hop-chain"),

  heroGameFromInput: $("hero-game-from-input"),
  heroGameFromAc: $("hero-game-from-ac"),
  heroGameFromAvatar: $("hero-game-from-avatar"),
  heroGameToInput: $("hero-game-to-input"),
  heroGameToAc: $("hero-game-to-ac"),
  heroGameToAvatar: $("hero-game-to-avatar"),
  btnHeroGameSwap: $("btn-hero-game-swap"),
  btnHeroStartChallenge: $("btn-hero-start-challenge"),

  heroGameDaily: $("hero-game-daily"),
  heroGameDailyFromAvatar: $("hero-game-daily-from-avatar"),
  heroGameDailyFromName: $("hero-game-daily-from-name"),
  heroGameDailyToAvatar: $("hero-game-daily-to-avatar"),
  heroGameDailyToName: $("hero-game-daily-to-name"),
  heroGameDailyPair: $("hero-game-daily-pair"),
  heroGameDailyState: $("hero-game-daily-state"),
  btnHeroDailyRetry: $("btn-hero-daily-retry"),
  btnHeroPlayDaily: $("btn-hero-play-daily"),
  heroGameRivals: $("hero-game-rivals"),
  heroGameRivalsList: $("hero-game-rivals-list"),
  heroGameDivider: $("hero-game-divider"),

  btnClearGraph: $("btn-clear-graph"),
  btnCopyLink: $("btn-copy-link"),
  btnExportPng: $("btn-export-png"),
  btnExportJson: $("btn-export-json"),
  btnFindPath: $("btn-find-path"),
  btnCompareMode: $("btn-compare-mode"),
  btnBubbleSets: $("btn-bubble-sets"),
  btnSearchOpen: $("btn-search-open"),

  canvasZoomCluster: $("canvas-zoom-cluster"),
  btnZoomIn: $("btn-zoom-in"),
  btnZoomOut: $("btn-zoom-out"),
  btnFitView: $("btn-fit-view"),
  btnFocusSeed: $("btn-focus-seed"),

  roleFilterSegment: $("role-filter-segment"),

  objectActionBar: $("object-action-bar"),
  objActionExpand: $("obj-action-expand"),
  objActionDeepen: $("obj-action-deepen"),
  objActionFocus: $("obj-action-focus"),
  objActionGenius: $("obj-action-genius"),

  companionPanel: $("companion-panel"),

  artistSidebar: $("artist-sidebar"),
  sidebarAvatar: $("sidebar-avatar"),
  sidebarName: $("sidebar-name"),
  sidebarMeta: $("sidebar-meta"),
  sidebarTracks: $("sidebar-tracks"),
  sidebarRoleBreakdownTile: $("sidebar-rolebreakdown-tile"),
  sidebarRoleChips: $("sidebar-role-chips"),
  sidebarPathTile: $("sidebar-path-tile"),
  sidebarPathTrack: $("sidebar-path-track"),
  sidebarEndpointsTile: $("sidebar-endpoints-tile"),
  sidebarEndpointsTrack: $("sidebar-endpoints-track"),
  sidebarClose: $("sidebar-close"),

  candidateOverlay: $("candidate-overlay"),
  candidateList: $("candidate-list"),
  candidateClose: $("candidate-close"),

  pathPanel: $("path-panel"),
  pathPanelClose: $("path-panel-close"),
  pathFromInput: $("path-from-input"),
  pathToInput: $("path-to-input"),
  btnSwapPath: $("btn-swap-path"),
  btnRunPath: $("btn-run-path"),
  btnClearPath: $("btn-clear-path"),
  hopChain: $("hop-chain"),

  comparePanel: $("compare-panel"),
  comparePanelClose: $("compare-panel-close"),
  compareTitle: $("compare-title"),
  comparePair: $("compare-pair"),
  compareTraceLabel: $("compare-trace-label"),
  compareHopChain: $("compare-hop-chain"),
  compareList: $("compare-list"),

  nodeSearchOverlay: $("node-search-overlay"),
  nodeSearchInput: $("node-search-input"),
  nodeSearchResults: $("node-search-results"),
  nodeSearchStatus: $("node-search-status"),
  btnNodeSearch: $("btn-node-search"),

  graphA11yNodeList: $("graph-a11y-node-list"),
  graphA11yNeighborList: $("graph-a11y-neighbor-list"),
  graphA11yNeighborsHeading: $("graph-a11y-neighbors-heading"),

  connectSurface: $("connect-surface"),
  connectTitleStart: $("connect-title-start"),
  connectTitleGoal: $("connect-title-goal"),
  connectParPill: $("connect-par-pill"),
  connectParValue: $("connect-par-value"),
  connectRivalPill: $("connect-rival-pill"),
  connectRivalText: $("connect-rival-text"),
  connectTimerValue: $("connect-timer-value"),
  connectHopsValue: $("connect-hops-value"),
  connectPoleFrom: $("connect-pole-from"),
  connectPoleFromName: $("connect-pole-from-name"),
  connectPoleTo: $("connect-pole-to"),
  connectPoleToName: $("connect-pole-to-name"),
  connectProgress: $("connect-progress"),
  connectPips: $("connect-pips"),
  connectProgressLabel: $("connect-progress-label"),
  connectEndpoints: $("connect-endpoints"),
  connectEndpointsSummary: $("connect-endpoints-summary"),
  connectStartBtn: $("connect-start-btn"),
  connectStartInput: $("connect-start-input"),
  connectStartAc: $("connect-start-ac"),
  connectGoalInput: $("connect-goal-input"),
  connectGoalAc: $("connect-goal-ac"),
  connectCanvas: $("connect-canvas"),
  connectStageEmpty: $("connect-stage-empty"),
  connectZoomIn: $("connect-zoom-in"),
  connectZoomOut: $("connect-zoom-out"),
  connectFit: $("connect-fit"),
  connectAddInput: $("connect-add-input"),
  connectAddAc: $("connect-add-ac"),
  connectAddBtn: $("connect-add-btn"),
  connectLineList: $("connect-line-list"),
  connectBrowse: $("connect-browse"),
  connectBrowseLabel: $("connect-browse-label"),
  connectBrowseChips: $("connect-browse-chips"),
  connectUndo: $("connect-undo"),
  connectReset: $("connect-reset"),
  connectGiveUp: $("connect-give-up"),
  connectShare: $("connect-share"),
  connectLockin: $("connect-lockin"),
  connectFinishLabel: $("connect-finish-label"),
  connectFinishScore: $("connect-finish-score"),
  connectFinishDetail: $("connect-finish-detail"),
  connectLeaderboard: $("connect-leaderboard"),

  gameLeaderboardSurface: $("game-leaderboard-surface"),
  lbTabSeason: $("lb-tab-season"),
  lbTabChallenge: $("lb-tab-challenge"),
  lbScopeLabel: $("lb-scope-label"),
  lbList: $("lb-list"),
  lbEmpty: $("lb-empty"),
  gameProfileSurface: $("game-profile-surface"),
  profileSignedOut: $("profile-signed-out"),
  profileCard: $("profile-card"),
  pfAvatar: $("pf-avatar"),
  pfName: $("pf-name"),
  pfRank: $("pf-rank"),
  pfElo: $("pf-elo"),
  pfGames: $("pf-games"),
  pfBadges: $("pf-badges"),
  pfBadgeList: $("pf-badge-list"),
  pfBadgesEmpty: $("pf-badges-empty"),
  pfHistory: $("pf-history"),
  pfHistoryEmpty: $("pf-history-empty"),
  pfEditName: $("pf-edit-name"),
  pfShare: $("pf-share"),

  adminPanel: $("admin-panel"),
  adminFromInput: $("admin-from-input"),
  adminFromAc: $("admin-from-ac"),
  adminToInput: $("admin-to-input"),
  adminToAc: $("admin-to-ac"),
  adminPublishDaily: $("admin-publish-daily"),
  adminStatus: $("admin-status"),

  gameChallengesSurface: $("game-challenges-surface"),
  chTabAll: $("ch-tab-all"),
  chTabDaily: $("ch-tab-daily"),
  chTabCustom: $("ch-tab-custom"),
  chGrid: $("ch-grid"),
  chEmpty: $("ch-empty"),
  chMore: $("ch-more"),
  chSearchInput: $("ch-search-input"),
  chSearchClear: $("ch-search-clear"),

  gameSeasonSurface: $("game-season-surface"),
  snName: $("sn-name"),
  snCountdown: $("sn-countdown"),
  snYou: $("sn-you"),
  snProgressFill: $("sn-progress-fill"),
  snDates: $("sn-dates"),
  snPodium: $("sn-podium"),
  snPodiumEmpty: $("sn-podium-empty"),
  snAchCount: $("sn-ach-count"),
  snAchHint: $("sn-ach-hint"),
  snAchGrid: $("sn-ach-grid"),

  btnSettingsOpen: $("btn-settings-open"),
  settingsPanel: $("settings-panel"),
  settingsBox: $("settings-box"),
  settingsPanelClose: $("settings-panel-close"),
  settingsThemeSelect: $("settings-theme-select"),
  settingsLangSelect: $("settings-lang-select"),
  settingsSignedOutHint: $("settings-signed-out-hint"),
  settingsMisconfiguredHint: $("settings-misconfigured-hint"),
  settingsCards: $("settings-cards"),
  settingsGeniusInput: $("settings-genius-input"),
  settingsGeniusConnectBtn: $("settings-genius-connect-btn"),
  settingsGeniusDisconnectBtn: $("settings-genius-disconnect-btn"),
  settingsGeniusStatus: $("settings-genius-status"),
  settingsEnrichmentToggle: $("settings-enrichment-toggle"),
};
